blank_issues_enabled: false
contact_links:
  - name: 🙋 Ask a question
    url: https://viacomcbs.enterprise.slack.com/archives/C03FD6SB940
    about: Ask questions and discuss with engineers on Slack
